# Generated by Django 3.1.7 on 2021-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_mechtaskusergroup_uses_proposed_payment_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtaskusergroup',
            name='can_change_algorithm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechtaskusergroup',
            name='can_change_attributes',
            field=models.BooleanField(default=False),
        ),
    ]
