# Generated by Django 3.1.7 on 2021-03-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210305_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtaskstudentsample',
            name='decision_tree_prediction',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechtaskstudentsample',
            name='kneighbors_prediction',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechtaskstudentsample',
            name='lasso_prediction',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechtaskstudentsample',
            name='linear_regression_prediction',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechtaskstudentsample',
            name='random_forest_prediction',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechtaskstudentsample',
            name='ridge_prediction',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechtaskstudentsample',
            name='svm_reg_prediction',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='real_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
