# Generated by Django 3.1.7 on 2021-03-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210315_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtaskusergroup',
            name='attention_check_statement',
            field=models.CharField(default='Type what you see here', max_length=500),
            preserve_default=False,
        ),
    ]
