# Generated by Django 3.1.7 on 2021-03-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_mechtaskusergroup_attention_check_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtasksurveyestimate',
            name='real_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechtasksurveyestimate',
            name='model_estimate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
