# Generated by Django 3.1.7 on 2021-03-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210326_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtaskalgorithm',
            name='average_error',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
