# Generated by Django 3.1.7 on 2021-03-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_mechtaskalgorithm_average_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechtaskalgorithm',
            name='average_error',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
