# Generated by Django 3.1.7 on 2021-03-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210328_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechtaskalgorithm',
            name='average_error',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='decision_tree_prediction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='kneighbors_prediction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='lasso_prediction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='linear_regression_prediction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='minutesPerWeekEnglish',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='random_forest_prediction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='real_score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='ridge_prediction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtaskstudentsample',
            name='svm_reg_prediction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtasksurveyestimate',
            name='model_estimate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtasksurveyestimate',
            name='real_score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mechtasksurveyestimate',
            name='user_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mechtasksurveyresponse',
            name='model_estimate_average_error',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mechtasksurveyresponse',
            name='self_estimate_average_error',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
