# Generated by Django 3.1.7 on 2021-03-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210328_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechtasksurveyresponse',
            old_name='model_estimates_for_bonus_calc',
            new_name='use_model_estimates_for_bonus_calc',
        ),
    ]
