# Generated by Django 3.1.7 on 2021-04-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210328_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtaskusergroup',
            name='follow_up_questions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
