# Generated by Django 3.1.7 on 2021-04-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_mechtaskusergroup_follow_up_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechtaskusergroup',
            name='follow_up_questions',
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
