# Generated by Django 3.1.7 on 2021-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210405_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='average_deviation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
