# Generated by Django 3.1.7 on 2021-04-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_mechtasksurveyresponse_average_deviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='placebo_selected_algorithm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placebo_response', to='webapp.mechtaskalgorithm'),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='placebo_selected_attributes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
