# Generated by Django 3.1.7 on 2021-04-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20210405_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechtasksurveyresponse',
            old_name='placebo_selected_algorithm',
            new_name='user_selected_algorithm',
        ),
        migrations.RenameField(
            model_name='mechtasksurveyresponse',
            old_name='placebo_selected_attributes',
            new_name='user_selected_attributes',
        ),
    ]
