# Generated by Django 3.1.7 on 2021-04-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210405_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechTaskCustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('attributes', models.CharField(max_length=500)),
                ('average_error', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mechtasksurveyestimate',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.mechtaskstudentsample'),
        ),
        migrations.CreateModel(
            name='MechTaskCustomModelSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('real_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('linear_regression_prediction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mechtaskcustommodel')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mechtaskstudentsample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mechtasksurveyestimate',
            name='custom_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.mechtaskcustommodelsample'),
        ),
    ]
