# Generated by Django 3.1.7 on 2021-04-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_mechtasksurveyresponse_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtaskusergroup',
            name='allow_only_10_percentile_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechtaskusergroup',
            name='should_use_model_estimates_only_for_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
