# Generated by Django 3.1.7 on 2021-04-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20210425_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechtaskusergroup',
            old_name='allow_only_10_percentile_change',
            new_name='only_10_percentile_change',
        ),
        migrations.RenameField(
            model_name='mechtaskusergroup',
            old_name='should_use_model_estimates_only_for_bonus',
            new_name='use_model_estimates_only',
        ),
    ]
