# Generated by Django 3.1.7 on 2021-04-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20210425_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtaskusergroup',
            name='use_freely',
            field=models.BooleanField(default=False),
        ),
    ]
