# Generated by Django 3.1.7 on 2021-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_mechtasksurveyresponse_user_agreed_to_take_only_once'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechtasksurveyresponse',
            old_name='age_bracket',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='mechtasksurveyresponse',
            old_name='race_ethnicity',
            new_name='race',
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='confidence_in_math',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='prev_mturk_algo_participation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='prev_mturk_algo_participation_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
