# Generated by Django 3.1.7 on 2021-04-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20210428_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechtasksurveyresponse',
            name='prev_mturk_algo_participation',
        ),
    ]
