# Generated by Django 3.1.7 on 2021-08-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_remove_mechtasksurveyresponse_prev_mturk_algo_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='human_aae',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='model_aae',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='used_model_for_bonus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='user_first_instruction_ans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='user_last_instruction_ans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='user_understood_first_instruction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechtaskusergroup',
            name='in_production',
            field=models.BooleanField(default=True),
        ),
    ]
