# Generated by Django 3.1.7 on 2021-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_auto_20210901_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='model_performance_as_per_user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mechtasksurveyresponse',
            name='model_performance_correctly_identified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
